import Head from 'next/head'
import { Box, Container, Grid, Switch } from '@material-ui/core'

export default function Home() {
  return (
    <Container maxWidth="sm">
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid container >
        <Grid item xs={12} style={{ border: '2px solid blue' }} >
          <Box>
            Hello
            <Switch
              color="primary"
              name="checkedB"
              inputProps={{ 'aria-label': 'primary checkbox' }}
            />
          </Box>
        </Grid>
        <Grid container item xs={6} style={{ border: '2px solid red' }}>
          <Box>
            Hello
            <Switch
              color="primary"
              name="checkedB"
              inputProps={{ 'aria-label': 'primary checkbox' }}
            />
          </Box>
        </Grid>
      </Grid >
    </Container >
  )
}
